### PR TITLE
CLI Tool Documentation and Scoping

### PR DESCRIPTION
**Pull request by andorsk**
CLI Tool Documentation and Scoping. Related to https://github.com/TBD54566975/ssi-sdk/issues/150 and https://github.com/TBD54566975/ssi-sdk/issues/150

### CODE REVIEW

**Comment by andorsk** [comment]
Starting to outline things out. Not ready to review but putting draft here in case anyone is interested in commenting.

**Comment by nitro-neal** [comment]
Looking great so far, I'm liking the 1st and 2nd order commands

**Comment by andorsk** [comment]
Might be doing something similar for the `ssi-service`

**Comment by decentralgabe** [comment]
closing for now, fine to re open if there's future interest

**Pull request closed without merging**
