### PR TITLE
Fix/did web create key

### PR DESCRIPTION
**Pull request by LiranCohen**
Was fiddling with did:web and noticed that the owner key ID and Controller were mismatched within the CreateDoc function.

Searched around and saw that it was also mismatched on the did:peer resolve method.

### CODE REVIEW

**Review by decentralgabe — APPROVED** [review]
thank you!

**Review by andresuribe87 — APPROVED** [review]
Thanks for fixing! Would you mind adding a test that failed before these changes were made?

**Comment by LiranCohen** [comment]
> Thanks for fixing! Would you mind adding a test that failed before these changes were made?

Yup I could do that.

**Comment by LiranCohen** [comment]
Added tests, let me know if you'd like me to modify it or add to it in any way to enhance overall testing.

Screenshot 2023-07-14 at 4 54 22 PM
Screenshot 2023-07-14 at 5 02 59 PM

This is what it looked like failing on main.

cc @andresuribe87

**Review by andresuribe87 — APPROVED** [review]
Amazing thanks!

**Comment by LiranCohen** [comment]
Rebased main and pushed.

**Comment by decentralgabe** [comment]
sorry @LiranCohen can you rebase once more and I'll merge?

**Comment by decentralgabe** [comment]
merging in https://github.com/TBD54566975/ssi-sdk/pull/430

**Pull request closed without merging**
